### ISSUE TITLE
GET nutrients from FDC API

### ISSUE THREAD

**Issue by entin-hun** [szekelyisz/ffd-ui#1]
http://localhost:9000/#/ opens with: 

> [vite] Internal server error: Failed to resolve entry for package "/opt/ffd-ui/src/fdc_api/generated". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "/opt/ffd-ui/src/fdc_api/generated". The package may have incorrect main/module/exports specified in its package.json.
>   Plugin: vite:import-analysis
>   File: /opt/ffd-ui/src/components/NutrientCharts.vue
>       at packageEntryFailure (/opt/ffd-ui/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:40970:11)
>       at resolvePackageEntry (/opt/ffd-ui/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:40966:9)
>       at tryResolveFile (/opt/ffd-ui/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:40682:38)
>       at tryFsResolve (/opt/ffd-ui/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:40664:16)
>       at Context.resolveId (/opt/ffd-ui/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:40552:56)
>       at Object.resolveId (/opt/ffd-ui/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:39254:55)
>       at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
>       at async Context.resolve (/opt/ffd-ui/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:39028:23)
>       at async Object.resolveId (/opt/ffd-ui/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:39254:32)
>       at async TransformContext.resolve (/opt/ffd-ui/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:39028:23)

**Comment by szekelyisz** [comment]
You need to run `yarn` in `src/fdc_api/generated` to compile the FDC OpenAPI client library. Did that, but `yarn run quasar build` results in

```
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```

Most likely the server is out of memory and unable to compile the app. Try allocating more memory or compiling it on another machine. Works on my computer.

**Comment by entin-hun** [comment]
I tried to compile locally to then upload built files. In the local /generated folder, after successful `yarn` and `yarn run quasar build`, `quasar dev` results in Running @quasar/cli v2.4.1:
> Error  Unknown command "dev"

Why?🤔

**Comment by szekelyisz** [comment]
> I tried to compile locally to then upload built files. In the local /generated folder, after successful `yarn` and `yarn run quasar build`, `quasar dev` results in Running @quasar/cli v2.4.1:
> > Error  Unknown command "dev"
> 
> Why?🤔

You need to upload the contents of `dist/spa` into your webroot and have them served as static files.

**Comment by entin-hun** [comment]
I only have /esm in /dist 
<img width="221" alt="image" src="https://github.com/user-attachments/assets/43b5739e-83b8-42e0-a2cb-aa515abb4642">

**Comment by szekelyisz** [comment]
`dist/spa` relative to the root of this repo. `src/fdc_api/generated` is only the OpenAPI client library for accessing services provided by the FDC. `yarn build` in the root will generate `dist/spa`. Put everything in there into your webroot.

**Comment by entin-hun** [comment]
So I uploaded dist/spa and src/fdc_api/generated:
<img width="961" alt="image" src="https://github.com/user-attachments/assets/e7701f11-3a3e-433c-889c-bf6dd1994ba8">
But quasar dev still results in 

> Error Unknown command "dev"

Why?🤔

**Comment by szekelyisz** [comment]
You don't need to run any command on the server. Just upload the compiled files, point your web server to the directory and you should be good. You don't need `src/fdc_api` either.

**Comment by entin-hun** [comment]
[Here's an example page](https://package.trace.market/?tokenId=65911128804176085630688883491619779598734956697428681996219229266732492927689#/). In the Network tab, **why the FDC request is missing**?
Within /src/fdc_api/generated, I only ran yarn (nothing with quasar, that package isn't known that level), then lint, format and build in the webroot.

**Comment by szekelyisz** [comment]
> [Here's an example page](https://package.trace.market/?tokenId=65911128804176085630688883491619779598734956697428681996219229266732492927689#/). In the Network tab, **why the FDC request is missing**? Within /src/fdc_api/generated, I only ran yarn (nothing with quasar, that package isn't known that level), then lint, format and build in the webroot.

I do see a request to FDC when I load that page:

![image](https://github.com/user-attachments/assets/44fd5e8a-f3bc-458d-b38c-3b1628acb959)
